name: Tests and Linting
on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn

      - name: Tests
        run: yarn test

      - name: Linting
        run: yarn lint